### ISSUE TITLE
After installing via pip it complains about missing "patterns" directory

### ISSUE THREAD

**Issue by freshteapot** [finklabs/korg#1]
```
File "/usr/local/lib/python2.7/dist-packages/korg/pattern.py", line 12, in __init__
    self.pattern_dict = self._load_patterns(folders, pattern_dict)
  File "/usr/local/lib/python2.7/dist-packages/korg/pattern.py", line 47, in _load_patterns
    for file in os.listdir(folder):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/patterns'
```
In the code [pattern.py](https://github.com/kaeru-repo/korg/blob/master/korg/pattern.py#L11) there is a hardcoded look up of "../patterns".

Option 1:
We could leave it how it is and put it in try catch.

Option 2:
Remove the lookup and alter the readme / examples to show that user needs to set the path to the patterns directory.

Hopefully you will get a patch from me sooner than later.

**Comment by markfink** [comment]
not sure how relevant this still is for you. I had similar issues with the released version (0.0.3). I checked in all the code and made a new release (0.0.5). import_korg_paterns=True works for me. I hope this fixes your issue too.
